version: "2.4"

services:
  app:
    build: .
    ports:
      - "10001:10000"
    environment:
      FLASK_ENV: "production"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared2
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKENE}
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
